### PR TITLE
do not activate postgres addon by default

### PR DESCRIPTION
**Pull request by asymmetric**
makes it hard to use any other db, or no db at all

### CODE REVIEW

**Comment by gjaldon** [comment]
@asymmetric does removing this mean that we will need to manually add postgres as an addon on heroku?

**Comment by asymmetric** [comment]
Yes, it does. I think that makes sense though. I understand Postgres is the default option in Phoenix, but why force it?

**Comment by ericmj** [comment]
The addon will only be added when the heroku app is created, still I am +1 for removing this default.

**Comment by gjaldon** [comment]
Thanks for the PR @asymmetric and for your input @ericmj!

**Pull request merged**
