### PR TITLE
Change default compile to use the deploy target to be compatible with…

### LINKED ISSUE #75: Change default compile file to use webpack instead of brunch when Phoenix 1.4 is released
Please see https://github.com/phoenixframework/phoenix/issues/2827

### PR DESCRIPTION
**Pull request by behe**
… both brunch (phoenix < 1.4.0) and webpack (phoenix >= 1.4.0)

Fixes #75

### CODE REVIEW

**Comment by effektz** [comment]
🚀 👍

**Comment by jesseshieh** [comment]
@gjaldon, have you had a chance to take a look at this yet?

**Comment by gjaldon** [comment]
Thanks for the contribution @behe 💜 Sorry I'm late to this. Been a while since I have been deploying a Phoenix app to Heroku

**Comment by jesseshieh** [comment]
@gjaldon would you be interested at all in having some extra maintainers around to help you? I'm the founder of gigalixir.com and we use this buildpack heavily so we'd be interested in contributing more actively. Thanks for making this great buildpack!

**Pull request merged**
