### PR TITLE
Update the config

### PR DESCRIPTION
**Pull request by vysogot**
Take latest versions and point to current phx executable and assets directory

### CODE REVIEW

**Comment by iloveitaly** [comment]
@gjaldon any thoughts here? Would be great to have these defaults in the master branch.

**Comment by gjaldon** [comment]
@vysogot thank you for the PR 💜

**Comment by jesseshieh** [comment]
@gjaldon @vysogot I think this may have broken some deploys. I am getting the following error now when I deploy. Do you mind if I revert this while we continue investigating? 
```
-----> Installing binaries
       Using cached node ...
       Installing Node ...
remote: mv: cannot stat ‘/tmp/node-v-linux-x64/*’: No such file or directory
```

**Comment by jesseshieh** [comment]
Looks like reverting fixed the error. I think issue was the node_version being blank, but I think it would be a problem to even bump the default node_version since a lot of apps probably rely on the defaults and might not be able to tolerate an automatic upgrade. @vysogot is there some way to modify the defaults for "new" apps without changing the settings for existing apps?

**Pull request merged**
