### PR TITLE
Add support for umbrella project.

### PR DESCRIPTION
**Pull request by seantanly**
Add support for phoenix under umbrella project.

Fixes issue https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/21

### CODE REVIEW

**Comment by bhserna** [comment]
Hi @seantanly, I am needing also a solution for the issue #21, but I can't make your fix to work form me =( ... 

I am just adding a file `phoenix_static_buildpack.config` with...

```
phoenix_relative_path="apps/my_phoenix_web_app"
```

And watching the logs all goes well but when I visit the app in the web browser the assets are not there.

**Comment by seantanly** [comment]
Hi @bhserna, are you able to share on Github a stripped down version of your app so that I can take a look?

**Comment by bhserna** [comment]
@seantanly I upload a test app here https://github.com/bhserna/heroku-build-pack-test-case ... I removed all the application code, but is basically the same configuration.

Thanks for your help!

**Comment by seantanly** [comment]
@bhserna are you also using the elixir buildpack from https://github.com/HashNuke/heroku-buildpack-elixir ?

If so, you should specify the version of Elixir. The buildpack is using Elixir 1.2.2 by default which contains some bugs that might be interfering with the assets building. Define your own `elixir_buildpack.config` such as the following.

```
# Erlang version
erlang_version=18.2.1

# Elixir version
elixir_version=1.2.3

# Always rebuild from scratch on every deploy?
always_rebuild=false

# Export heroku config vars
config_vars_to_export=(DATABASE_URL)

# A command to run right after compiling the app
post_compile="pwd"
```

Meanwhile, before my pull request is merged into the master here, you might want to point to my version of the phoenix buildpack which contains the fix.

https://github.com/seantanly/heroku-buildpack-phoenix-static

**Comment by seantanly** [comment]
@bhserna You might be simply missing the following in your `apps/food_shop_web/mix.exs`.

```elixir
   def project do
     [app: :food_shop_web,
      version: "0.0.1",
+     build_path: "../../_build",
+     config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
```
I have this version working on my Dokku deployment. https://github.com/seantanly/heroku-build-pack-test-case

Note that I'm pointing to my version of phoenix buildpack which contains the fix since this fix isn't merged into official master yet.

**Comment by bhserna** [comment]
@seantanly thanks!!  your fix and those two lines make it work for me!!

**Comment by seantanly** [comment]
@bhserna you're welcome! Let's hope the fix gets merged into master soon. :) @gjaldon ;)

**Comment by gjaldon** [comment]
Thanks guys for testing this out! @seantanly @bhserna and thanks @seantanly for the PR! :+1:

**Pull request merged**
