### PR TITLE
Bump node_version to 5.3.0

### PR DESCRIPTION
**Pull request by col**
This addresses an issue when trying to compile assets in when using Phoenix 1.1.0.

See https://github.com/phoenixframework/phoenix/issues/1410 for more details.

### CODE REVIEW

**Comment by chrismcg** [comment]
Should this set the npm version to the most recent too?

**Comment by col** [comment]
Yeah I think you're right. Bumping the node version was enough to fix my
problem but they should be upgraded together. I'll update the pull request
tonight.

**Comment by seantanly** [comment]
Simply bumping the Node version doesn't seem to work for me when upgrading to Phoenix 1.1.2. 

I have raised a separate issue https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/15.

**Comment by gjaldon** [comment]
Thanks for the PR @col!

**Pull request merged**
